apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
     app: db
spec:
 type: ClusterIP
 ports:
  - name: "db_service"
    port: 5432
    targetPort: 5432
 selector:
    matchLabels:
      app: db
  